---

- fail:
    msg: Unsupported package manager
  when: ansible_pkg_mgr != 'apt'

- name: Install the required packages
  package:
    name:  '{{ item }}'
    state: present
  with_items:
    - apt-transport-https
    - curl
    - debian-archive-keyring

- name: Add repository APT key using apt_key
  apt_key:
    url:   '{{ gitlab_runner__apt_key }}'
    state: present
  register: _gitlab_runner__apt_key
  ignore_errors: '{{ httpproxy is defined }}'

- name: Add repository APT key using http proxy
  shell: 'curl --location --proxy "{{ httpproxy }}" "{{ gitlab_runner__apt_key }}" | apt-key add -'
  when: _gitlab_runner__apt_key|failed and httpproxy is defined

- name: Add apt repository
  apt_repository:
    repo:         '{{ gitlab_runner__apt_repo }}'
    update_cache: True
    state:        present
