---

- name: Fail on bad package manager fact
  fail:
    msg: Unsupported package manager
  when: ansible_pkg_mgr != 'apt'
  tags: ['always']

- name: Install the required packages
  package:
    name:
      - apt-transport-https
      - curl
      - debian-archive-keyring
    state: present
  tags: ['gitlab-runner', 'gitlab-runner-install']

- name: Add docker repository GPG key to apt keyring
  apt_key:
    id: '{{ item.id }}'
    file: "{{ omit if item.state|d('present') != 'present' else '/tmp/gitlab_runner__gpg-'~item.id }}"
    state: "{{ item.state|d('present') }}"
  with_items: '{{ gitlab_runner__gpg_keys[ansible_os_family] }}'
  tags: ['gitlab-runner', 'gitlab-runner-install']

- name: Add apt repository
  apt_repository:
    repo: '{{ gitlab_runner__apt_repo }}'
    update_cache: true
    state: present
  tags: ['gitlab-runner', 'gitlab-runner-install']
