---
# tasks file for gitlab-runner

- name: Include the OS specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - defaults.yml
      skip: true
  tags: ['always']

- import_tasks: install.yml
  tags: ['gitlab-runner', 'gitlab-runner-install']

- import_tasks: configure.yml
  tags: ['gitlab-runner', 'gitlab-runner-configure']

- import_tasks: service.yml
  tags: ['gitlab-runner', 'gitlab-runner-service']

#- include_tasks: facts.yml
  #when: gitlab_runner__facts|bool
  #tags: ['gitlab-runner', 'gitlab-runner-facts']
